version: '3.9'

services:
  nodejs-app:
    build: ./
    #Este é o nome da imagem criada pelo Dockerfile.
    image: nodejs-app-image
    #Este é o nome do container que vai ser criado pelo docker-compose.
    container_name: nodejs-app-container
    ports:
      - "80:80"